Bug 1414255 - Enable bash 'strict mode' in all shell scripts
This makes some of the error checking in `runtest.sh` redundant.
The shebangs have also been made more consistent.

See:
http://redsymbol.net/articles/unofficial-bash-strict-mode/

diff --git a/bin/post_compile b/bin/post_compile
--- a/bin/post_compile
+++ b/bin/post_compile
@@ -1,5 +1,8 @@
-#!/bin/bash -e
+#!/usr/bin/env bash
 # Tasks run by the Heroku Python buildpack after the compile step.
+
+# Make non-zero exit codes & other errors fatal.
+set -euo pipefail
 
 # Make the current Git revision accessible at <site-root>/revision.txt
 echo $SOURCE_VERSION > ui/revision.txt
diff --git a/bin/run_gunicorn b/bin/run_gunicorn
--- a/bin/run_gunicorn
+++ b/bin/run_gunicorn
@@ -1,6 +1,7 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-set -e
+# Make non-zero exit codes & other errors fatal.
+set -euo pipefail
 
 SRC_DIR=$(dirname "$(dirname "${BASH_SOURCE[0]}")")
 cd $SRC_DIR
