Bug 1165229 - Heroku: Add option to make pre-deploy errors non-fatal
When first setting up a new app on Heroku, things like reporting the
deploy to New Relic will fail, since it requires that the app exist on
New Relic. However the app will only be created there once the Python
agent first reports app metadata, which won't happen until after the
deploy (there is no way to create the app via the web interface).

In addition, there may be cases in the future when stage/prod is broken,
and the pre-deploy tasks therefore fail, however we still want the
deploy to proceed.

To avoid needing to constantly edit this file, the environment variable
`IGNORE_PREDEPLOY_ERRORS` can now be set, in cases where the deploy
should continue even if there were errors. (Note this uses the bash 4.2+
`-v` option, see http://stackoverflow.com/a/18448624).

diff --git a/bin/pre_deploy b/bin/pre_deploy
--- a/bin/pre_deploy
+++ b/bin/pre_deploy
@@ -1,8 +1,13 @@
 #!/usr/bin/env bash
 # Tasks run after the Heroku buildpack compile, but prior to the deploy.
-# If failures occur, the deploy will not proceed.
+# Failures will block the deploy unless `IGNORE_PREDEPLOY_ERRORS` is set.
 
-set -euo pipefail
+if [[ -v IGNORE_PREDEPLOY_ERRORS ]]; then
+    echo "-----> PRE-DEPLOY: Warning: Ignoring errors during pre-deploy!"
+else
+    # Make non-zero exit codes & other errors fatal.
+    set -euo pipefail
+fi
 
 echo "-----> PRE-DEPLOY: Running Django migration..."
 ./manage.py migrate --noinput
